### ISSUE TITLE
Segfault at startup (Player::_msound is null)

### ISSUE THREAD

**Issue by simonArchipoff** [mincequi/qLouder#6]
Hello,
I have a problem to start the software, something seems to be not initialized.
Please note that I have a weird configuration as I use pipewire-pulse instead of pulseaudio, maybe that's an important factor ?
I have no clue what's going on and my understanding of those lib are rather small, please ask me if you want more data regarding the problem.
Here a coredump :
[core-dump.zip](https://github.com/mincequi/qLouder/files/10004751/core-dump.zip)

Regards,
Simon

**Comment by mincequi** [comment]
Hey,
thanks for your feedback.
Please check latest master/main branch. There had been an uninitialised object.

**Comment by simonArchipoff** [comment]
It's all good now :-)
you're welcome
